# Generated by Django 6.0.2 on 2026-02-09 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('location_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('location_name', models.CharField(max_length=200)),
                ('location_city', models.CharField(max_length=100)),
                ('location_state', models.CharField(max_length=100)),
                ('location_country', models.CharField(max_length=100)),
                ('location_zip', models.CharField(max_length=20)),
                ('location_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_description', models.TextField()),
            ],
            options={
                'ordering': ['location_name'],
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('property_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True)),
                ('property_name', models.CharField(max_length=200)),
                ('property_type', models.CharField(choices=[('Villa', 'Villa'), ('Condo', 'Condo'), ('Chalet', 'Chalet'), ('Cabin', 'Cabin'), ('Loft', 'Loft'), ('Penthouse', 'Penthouse'), ('House', 'House'), ('Townhouse', 'Townhouse'), ('Suite', 'Suite')], max_length=50)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=3)),
                ('max_guests', models.IntegerField()),
                ('price_per_night', models.DecimalField(decimal_places=2, max_digits=10)),
                ('property_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='rentals.location')),
            ],
            options={
                'verbose_name_plural': 'Properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=20, unique=True)),
                ('image_url', models.URLField(max_length=500)),
                ('image_caption', models.CharField(blank=True, max_length=300)),
                ('image_order', models.IntegerField(default=0)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rentals.property')),
            ],
            options={
                'ordering': ['image_order', 'image_id'],
            },
        ),
    ]
